name: Deploy Docker to Cloud run

on:
  push:
    branches:
    - main
  
env:
  PROJECT_ID: manu-twitter-bot
  SERVICE_NAME: twitter-bot
  IMAGE_NAME: cloud-run

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - run: gcloud --quiet auth configure-docker us-east1-docker.pkg.dev
    
    - name: Add secrets to files
      run: |
        mkdir config
        echo "${{ secrets.GCP_CREDENTIALS_QUOTES_ESCAPED }}" > config/google_creds.json
        echo "${{ secrets.CONFIG }}" > config/config.ini

    - name: Build
      run: docker build --tag "us-east1-docker.pkg.dev/$PROJECT_ID/$SERVICE_NAME/$SERVICE_NAME:$GITHUB_SHA" .

    - name: Push
      run: docker push "us-east1-docker.pkg.dev/$PROJECT_ID/$SERVICE_NAME/$SERVICE_NAME:$GITHUB_SHA"

    - id: 'Deploy'
      uses: 'google-github-actions/deploy-cloudrun@v0'
      with:
        service: 'hello-cloud-run'
        image: "us-east1-docker.pkg.dev/$PROJECT_ID/$SERVICE_NAME/$SERVICE_NAME:$GITHUB_SHA"